# Generated by Django 5.0.6 on 2024-08-20 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_learner_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCORMUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorm_player_id', models.CharField(max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SCORM User Profile',
                'verbose_name_plural': 'SCORM User Profiles',
            },
        ),
    ]
