# Generated by Django 5.0.6 on 2024-08-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_scormuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormuserprofile',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
