# Generated by Django 5.1.1 on 2024-09-30 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinate_positions', to='organization.jobposition'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='job_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.jobposition'),
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organizationchange',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_org_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationchange',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organizationcontact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_units', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization.organizationunit'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='organization_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.organizationunit'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='organization.employeeprofile'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='organization.organizationunit'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['organization', 'parent'], name='organizatio_organiz_aa19f3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['organization', 'level'], name='organizatio_organiz_f0fb39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationunit',
            unique_together={('organization', 'name')},
        ),
    ]
