# Generated by Django 5.1.1 on 2024-09-13 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationunit',
            options={'ordering': ['organization', 'level', 'name']},
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='unit_type',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('DIVISION', 'Division'), ('DEPARTMENT', 'Department'), ('TEAM', 'Team'), ('SUB_TEAM', 'Sub Team'), ('PROJECT', 'Project'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='organizationunit',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['organization', 'parent'], name='organizatio_organiz_aa19f3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationunit',
            index=models.Index(fields=['organization', 'level'], name='organizatio_organiz_f0fb39_idx'),
        ),
    ]
