# Generated by Django 5.1.1 on 2024-09-15 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organizationunit_options_and_more'),
        ('users', '0002_role_alter_scormuserprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='current_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_profile', to='users.userorganizationassignment'),
        ),
    ]
