# Generated by Django 5.0.6 on 2024-08-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificate_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='user_name',
        ),
    ]
