# Generated by Django 5.0.6 on 2024-08-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_remove_certificate_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
