# Generated by Django 5.0.6 on 2024-08-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_certificate_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
