# Generated by Django 5.0.6 on 2024-08-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_alter_certificateissuancelog_issued_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateissuancelog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
