# Generated by Django 5.1.1 on 2024-09-30 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualClassroomProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Provider Name')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Virtual Classroom Provider',
                'verbose_name_plural': 'Virtual Classroom Providers',
            },
        ),
        migrations.CreateModel(
            name='VirtualClassroomSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_type', models.CharField(choices=[('TEAMS', 'Microsoft Teams'), ('ZOOM', 'Zoom'), ('MEET', 'Google Meet')], max_length=10, verbose_name='Provider Type')),
                ('meeting_id', models.CharField(max_length=255, verbose_name='Meeting ID')),
                ('meeting_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meeting Password')),
                ('join_url', models.URLField(verbose_name='Join URL')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Is Recurring')),
                ('recurrence_pattern', models.JSONField(blank=True, null=True, verbose_name='Recurrence Pattern')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_virtual_sessions', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_sessions', to='courses.delivery')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtual_classroom.virtualclassroomprovider')),
            ],
            options={
                'verbose_name': 'Virtual Classroom Session',
                'verbose_name_plural': 'Virtual Classroom Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='VirtualClassroomAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('join_time', models.DateTimeField(blank=True, null=True, verbose_name='Join Time')),
                ('leave_time', models.DateTimeField(blank=True, null=True, verbose_name='Leave Time')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_attendances', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='virtual_classroom.virtualclassroomsession')),
            ],
            options={
                'verbose_name': 'Virtual Classroom Attendee',
                'verbose_name_plural': 'Virtual Classroom Attendees',
                'unique_together': {('session', 'user')},
            },
        ),
    ]
