# Generated by Django 5.0.6 on 2024-07-28 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursecategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursecategory'),
        ),
        migrations.AddField(
            model_name='coursedelivery',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursedelivery',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursedelivery',
            name='facilitators',
            field=models.ManyToManyField(related_name='facilitated_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursedelivery'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.learningresource'),
        ),
        migrations.AddField(
            model_name='scormregistration',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_registration', to='courses.enrollment'),
        ),
        migrations.AddField(
            model_name='scormresource',
            name='learning_resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_details', to='courses.learningresource'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course_delivery')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('enrollment',)},
        ),
        migrations.AlterUniqueTogether(
            name='learningprogress',
            unique_together={('enrollment', 'resource')},
        ),
    ]
