# Generated by Django 5.0.6 on 2024-08-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='scorm_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
