# Generated by Django 5.1.1 on 2024-09-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='resource_type',
            field=models.CharField(choices=[('SCORM', 'SCORM Package'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('LINK', 'External Link'), ('QUIZ', 'Quiz')], max_length=20),
        ),
    ]
