# Generated by Django 5.1.1 on 2024-09-30 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('INSTRUCTOR_LED', 'Instructor-led'), ('SELF_PACED', 'Self-paced')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
