# Generated by Django 5.0.6 on 2024-08-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_scorm_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='launch_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
