# Generated by Django 5.0.6 on 2024-08-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_learningresource_launch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormresource',
            name='scorm_package_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
