# Generated by Django 5.0.6 on 2024-08-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_scormresource_scorm_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
