# Generated by Django 5.1.1 on 2024-09-10 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycomponent',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_components', to='courses.deliverycomponent'),
        ),
        migrations.AlterField(
            model_name='deliverycomponent',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
    ]
