# Generated by Django 5.1.1 on 2024-09-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_deliverycomponent_parent_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
    ]
