# Generated by Django 5.0.6 on 2024-09-03 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_program_duration_program_exam_code_program_exam_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='programs',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.program'),
        ),
    ]
