# Generated by Django 5.1.1 on 2024-09-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
