# Generated by Django 5.1.1 on 2024-09-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcement_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementrecipient',
            name='specific_recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
